# Generated by Django 5.2.11 on 2026-03-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('LINK', 'Link'), ('YOUTUBE', 'YouTube'), ('DRAWING/BOOKS', 'Drawing (PDF/PNG)'), ('DXF', 'DXF (download)'), ('ANIMATION', 'Animation'), ('QUIZ', 'Quiz'), ('TELEGRAM', 'Telegram')], max_length=20),
        ),
    ]
