# Generated by Django 5.2.11 on 2026-03-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Sodda'), ('MEDIUM', 'O‘rtacha'), ('HARD', 'Qiyinroq')], default='EASY', max_length=10),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Sodda'), ('MEDIUM', 'O‘rtacha'), ('HARD', 'Qiyinroq')], default='EASY', max_length=10),
        ),
    ]
