# Generated by Django 5.2.11 on 2026-03-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question_difficulty_quizattempt_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_image',
            field=models.FileField(blank=True, null=True, upload_to='quiz_images/choices/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.FileField(blank=True, null=True, upload_to='quiz_images/questions/'),
        ),
    ]
