# Generated by Django 5.2.12 on 2026-03-28 13:00

import quizzes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_choice_choice_image_question_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_image',
            field=models.FileField(blank=True, null=True, upload_to=quizzes.models.choice_image_path),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Sodda'), ('MEDIUM', "O'rtacha"), ('HARD', 'Qiyinroq')], default='EASY', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.FileField(blank=True, null=True, upload_to=quizzes.models.question_image_path),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Sodda'), ('MEDIUM', "O'rtacha"), ('HARD', 'Qiyinroq')], default='EASY', max_length=10),
        ),
    ]
